export const TRY_AUTH_BEGIN = 'TRY_AUTH_BEGIN';
export const TRY_AUTH_SUCCESS = 'TRY_AUTH_SUCCESS';
export const TRY_AUTH_ERROR = 'TRY_AUTH_ERROR';

export const POST_DEVICE_TOKEN_BEGIN = 'POST_DEVICE_TOKEN_BEGIN';
export const POST_DEVICE_TOKEN_SUCCESS = 'POST_DEVICE_TOKEN_SUCCESS';
export const POST_DEVICE_TOKEN_ERROR = 'POST_DEVICE_TOKEN_ERROR';

export const NEXT_BOOK_WEEK = 'NEXT_BOOK_WEEK';
export const PREV_BOOK_WEEK = 'PREV_BOOK_WEEK';
export const BOOK_DATE_SELECTED = 'BOOK_DATE_SELECTED';
export const UPDATE_BOOK_WEEKS = 'UPDATE_BOOK_WEEKS';

export const NEXT_ACC_WEEK = 'NEXT_ACC_WEEK';
export const PREV_ACC_WEEK = 'PREV_ACC_WEEK';
export const ACC_DATE_SELECTED = 'ACC_DATE_SELECTED';
export const UPDATE_ACC_WEEKS = 'UPDATE_ACC_WEEKS';
export const UPDATE_TO_DATE = 'UPDATE_TO_DATE';

export const DELETE_EVENT_BEGIN = 'DELETE_EVENT_BEGIN';
export const DELETE_EVENT_SUCCESS = 'DELETE_EVENT_SUCCESS';
export const DELETE_EVENT_ERROR = 'DELETE_EVENT_ERROR';

export const FETCH_BOOKED_BEGIN = "FETCH_BOOKED_BEGIN";
export const FETCH_BOOKED_SUCCESS = 'FETCH_BOOKED_SUCCESS';
export const FETCH_BOOKED_FAILURE = 'FETCH_BOOKED_FAILURE';
export const ON_UPDATE_STATUS = 'ON_UPDATE_STATUS';
export const ON_BOOK_JOB_CALENDAR_SUCCESS = 'ON_BOOK_JOB_CALENDAR_SUCCESS';
export const ON_BOOK_JOB_CALENDAR_BEGIN = 'ON_BOOK_JOB_CALENDAR_BEGIN';
export const ON_BOOK_JOB_CALENDAR_ERROR = 'ON_BOOK_JOB_CALENDAR_ERROR';

export const FETCH_ACCEPT_BEGIN = "FETCH_ACCEPT_BEGIN";
export const FETCH_ACCEPT_SUCCESS = 'FETCH_ACCEPT_SUCCESS';
export const FETCH_ACCEPT_FAILURE = 'FETCH_ACCEPT_FAILURE';
export const ON_ACCEPT_JOB_SUCCESS = 'ON_ACCEPT_JOB_SUCCESS';

export const FETCH_SEARCH_BEGIN = "FETCH_SEARCH_BEGIN";
export const FETCH_SEARCH_SUCCESS = 'FETCH_SEARCH_SUCCESS';
export const FETCH_SEARCH_FAILURE = 'FETCH_SEARCH_FAILURE';

export const TOGGLE_SHOW_WEEKENDS = 'TOGGLE_SHOW_WEEKENDS';
export const FETCH_DECLINE_BEGIN = 'FETCH_DECLINE_BEGIN';
export const ON_DECLINE_JOB_SUCCESS = 'ON_DECLINE_JOB_SUCCESS';
export const FETCH_DECLINE_FAILURE = 'FETCH_DECLINE_FAILURE';

export const RESET_BOOK_JOBS_FOR_SELECTED_DATES = 'RESET_BOOK_JOBS_FOR_SELECTED_DATES';

export const UPDATE_JOB_BEGIN = 'UPDATE_JOB_BEGIN';
export const UPDATE_JOB_SUCCESS = 'UPDATE_JOB_SUCCESS';
export const UPDATE_JOB_ERROR = 'UPDATE_JOB_ERROR';

export const POST_PROTOCOL_BEGIN = 'POST_PROTOCOL_BEGIN';
export const POST_PROTOCOL_SUCCESS = 'POST_PROTOCOL_SUCCESS';
export const POST_PROTOCOL_ERROR = 'POST_PROTOCOL_ERROR';

export const UPDATE_ORDER = 'UPDATE_ORDER';
export const REMOVE_ORDER = 'REMOVE_ORDER';

export const UPDATE_FILER_INSTALLER = 'UPDATE_FILER_INSTALLER';
export const UPDATE_USER_NAME_FILTER = 'UPDATE_USER_NAME_FILTER';
export const INSERT_ALL_USER_NAMES_FILTER = 'INSERT_ALL_USER_NAMES_FILTER';

export const CLEAR_SEARCH_DATA = 'CLEAR_SEARCH_DATA';

export const SET_CONNECTION = 'SET_CONNECTION';

export const CLEAR_ALL_DATA = 'CLEAR_ALL_DATA';

export const SET_MESSAGES = 'SET_MESSAGES';

export const SET_ACTIVE_PAGE = 'SET_ACTIVE_PAGE';